machine:
  registries:
    mirrors:
      quay.io:
        endpoints:
          - https://quay.nanibot.net
      docker.io:
        endpoints:
          - https://registry-1.nanibot.net
      gcr.io:
        endpoints:
          - https://gcr.nanibot.net
      ghcr.io:
        endpoints:
          - https://ghcr.nanibot.net
      registry.k8s.io:
        endpoints:
          - https://registry-k8s.nanibot.net