#!/bin/bash
# VyOS and Services
virsh vcpupin VyOS 0 64 --config
virsh vcpupin VyOS 1 65  --config
virsh vcpupin VyOS 2 66 --config
virsh vcpupin VyOS 3 67 --config
virsh numatune VyOS --mode strict --nodeset 0 --config

virsh vcpupin Services 0 68 --config
virsh vcpupin Services 1 69  --config
virsh vcpupin Services 2 70 --config
virsh vcpupin Services 3 71 --config
virsh numatune Services --mode strict --nodeset 0 --config
