apiVersion: config.openshift.io/v1
kind: ImageTagMirrorSet
metadata:
  name: image-tag-mirror
spec:
  imageTagMirrors:
  - mirrorSourcePolicy: NeverContactSource
    mirrors:
    - quay.nanibot.net
    source: quay.io
  - mirrorSourcePolicy: NeverContactSource
    mirrors:
    - registry-1.nanibot.net
    source: registry-1.docker.io
  - mirrorSourcePolicy: NeverContactSource
    mirrors:
    - registry-k8s.nanibot.net
    source: registry.k8s.io
  - mirrorSourcePolicy: NeverContactSource
    mirrors:
    - gcr.nanibot.net
    source: gcr.io
  - mirrorSourcePolicy: NeverContactSource
    mirrors:
    - ghcr.nanibot.net
    source: ghcr.io
  - mirrorSourcePolicy: NeverContactSource
    mirrors:
    - openshift-ci.nanibot.net
    source: registry.ci.openshift.org